version: 1.2
workflows:
- name: MergeVCFs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MergeVCFs.wdl
  testParameterFiles:
- name: GetVCFs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetVCFs.wdl
  testParameterFiles:
- name: VisualizeSVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/VisualizeSVs.wdl
  testParameterFiles:
- name: JointCalling
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JointCalling.wdl
  testParameterFiles:
- name: OverlapStats
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/OverlapStats.wdl
  testParameterFiles:
- name: OverlapGraph
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/OverlapGraph.wdl
  testParameterFiles:
- name: VgIndex
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/VgIndex.wdl
  testParameterFiles:
- name: PhasedMerge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PhasedMerge.wdl
  testParameterFiles:
- name: TruvariIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntrasample.wdl
  testParameterFiles:
- name: TruvariBenchSample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariBenchSample.wdl
  testParameterFiles:
- name: PBAssembleWithHifiasm
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PBAssembleWithHifiasm.wdl
  testParameterFiles:
