version: 1.2
workflows:
- name: GetVCFs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetVCFs.wdl
  testParameterFiles:
- name: VisualizeSVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/VisualizeSVs.wdl
  testParameterFiles: