version: 1.2
workflows:
- name: GetVCFs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetVCFs.wdl
  testParameterFiles:
- name: VisualizeSVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/VisualizeSVs.wdl
  testParameterFiles:
- name: JointCalling
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JointCalling.wdl
  testParameterFiles:
- name: OverlapStats
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/OverlapStats.wdl
  testParameterFiles:
- name: OverlapGraph
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/OverlapGraph.wdl
  testParameterFiles: